name: Build Example App

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Example Android App
        run: cd examples/basic; ./gradlew assembleRelease

      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Copy App Artifact
        run: cp examples/basic/app/build/outputs/apk/release/app-release.apk app-${{ steps.package-version.outputs.current-version }}.apk

      - name: Upload App Artifact
        uses: actions/upload-artifact@v3
        with:
          path: app-${{ steps.package-version.outputs.current-version }}.apk
